package comun.protocolo;

public enum TipoProtocolo {

    //v1
    LOGIN,
    TRANSFERENCIA,
    CRIACAO_CONTA,
    EXTRATO,
    BUSCA_ESTADO,

    //v2
    //VISAO
    VISAO_LOGIN,
    VISAO_TRANSFERENCIA,
    VISAO_CRIACAO_CONTA,
    VISAO_EXTRATO,
    VISAO_BUSCA_ESTADO,
    //CONTROLE
    CONTROLE_LOGIN,
    CONTROLE_TRANSFERENCIA,
    CONTROLE_CRIACAO_CONTA,
    CONTROLE_EXTRATO,
    CONTROLE_BUSCA_ESTADO,
    //PERSISTENCIA
    PERSISTENCIA_LOGIN,
    PERSISTENCIA_TRANSFERENCIA,
    PERSISTENCIA_CRIACAO_CONTA,
    PERSISTENCIA_EXTRATO,
    PERSISTENCIA_BUSCA_ESTADO,
}
